title: "floirot"
baseURL: "https://floirot.github.io/"
languageCode: "sk"
theme: "hugo-floirot"

permalinks:
  # blog: "/:slugorcontentbasename/"
  term:
    ingredients: "/recipes/ingredient/:slug"
    types-of-food: "/recipes/type-of-food/:slug"

menu:
  main:
    - name: "Domov"
      pageRef: "/"
      weight: 10
    - name: "Recepty"
      pageRef: "/recipes"
      weight: 20
    #- name: "Blog"
    #  pageRef: "/blog"
    #  weight: 20
    - name: "PÃ­sanie"
      pageRef: "/writings"
      weight: 30
    #- name: "O mne"
    #  pageRef: "/about.md"
    #  weight: 40

taxonomies:
  #category: categories
  #tag: tags
  ingredient: ingredients
  type-of-food: types-of-food

# config .md -> .html parsing
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
    # ordered: true
  highlight:
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: "catppuccin-mocha"

# misc
capitalizeListTitles: false
enableRobotsTXT: true
disableKinds: ["taxonomy"]
